<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150202205200 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE in2code_in2timetape_domain_model_employee (persistence_object_identifier VARCHAR(40) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, timetapeid VARCHAR(255) NOT NULL, department VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE in2code_in2timetape_domain_model_holidayentitlement (persistence_object_identifier VARCHAR(40) NOT NULL, employee VARCHAR(40) DEFAULT NULL, year INT NOT NULL, daysentitledthisyear DOUBLE PRECISION NOT NULL, remainingdaysfromlastyear DOUBLE PRECISION NOT NULL, daysexpiredfromlastyear DOUBLE PRECISION NOT NULL, daystakenthisyear DOUBLE PRECISION NOT NULL, INDEX IDX_162086C05D9F75A1 (employee), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE in2code_in2timetape_domain_model_holidayrequest (persistence_object_identifier VARCHAR(40) NOT NULL, employee VARCHAR(40) DEFAULT NULL, requestid VARCHAR(255) NOT NULL, replacement VARCHAR(255) NOT NULL, datecreated DATETIME NOT NULL, dateupdated DATETIME NOT NULL, startdate DATETIME NOT NULL, enddate DATETIME NOT NULL, status INT NOT NULL, numberofdays DOUBLE PRECISION NOT NULL, INDEX IDX_B287AB115D9F75A1 (employee), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE in2code_in2timetape_domain_model_holidayentitlement ADD CONSTRAINT FK_162086C05D9F75A1 FOREIGN KEY (employee) REFERENCES in2code_in2timetape_domain_model_employee (persistence_object_identifier)");
		$this->addSql("ALTER TABLE in2code_in2timetape_domain_model_holidayrequest ADD CONSTRAINT FK_B287AB115D9F75A1 FOREIGN KEY (employee) REFERENCES in2code_in2timetape_domain_model_employee (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE in2code_in2timetape_domain_model_holidayentitlement DROP FOREIGN KEY FK_162086C05D9F75A1");
		$this->addSql("ALTER TABLE in2code_in2timetape_domain_model_holidayrequest DROP FOREIGN KEY FK_B287AB115D9F75A1");
		$this->addSql("DROP TABLE in2code_in2timetape_domain_model_employee");
		$this->addSql("DROP TABLE in2code_in2timetape_domain_model_holidayentitlement");
		$this->addSql("DROP TABLE in2code_in2timetape_domain_model_holidayrequest");
	}
}