#                                                                        #
# Routes configuration                                                   #
#                                                                        #
# This file contains the configuration for the MVC router.               #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the Flow manual for possible configuration options.    #
#                                                                        #

##
# Subroutes for the package In2code.In2timetape.
#
##
##
# Default subroutes
#
-
  name: 'Timetape2Mite'
  uriPattern: '{@controller}/{@action}(.{@format})'
  defaults:
    @package: 'In2code.In2timetape'
    @controller: 'Entitlement'
    @action: 'index'
    @format: 'html'

##
# Redirect to index action of given controller
#
-
  name: 'Timetape2Mite'
  uriPattern: '{@controller}'
  defaults:
    @package: 'In2code.In2timetape'
    @controller: 'Entitlement'
    @action: 'index'
    @format: 'html'

##
# Redirect to default action of default controller
#
-
  name: 'Timetape2Mite'
  uriPattern: ''
  defaults:
    @package: 'In2code.In2timetape'
    @controller: 'Entitlement'
    @action: 'index'
    @format: 'html'